

const initState = {
  categories: [
    { name: 'Action A', img: "./images/painter.png", userId: 'unknown' },
    { name: 'Action B', img: "./images/unicorn.png", userId: 'unknown' },
    { name: 'Food', img: "./images/diet.png", userId: 'unknown' },
    { name: "Dishes", img: "./images/dish.png", userId: 'unknown' },
    { name: "Pets", img: "./images/pet.png", userId: 'unknown' },
    { name: "Animals", img: "./images/chick.png", userId: 'unknown' },
    { name: "Clothes", img: "./images/clothes.png", userId: 'unknown' },
    { name: "Emotion", img:  "./images/emotions.png", userId: 'unknown' },
    { name: "Body", img:  "./images/anatomy.png", userId: 'unknown' },
    { name:  "Space", img:  "./images/solar-system.png", userId: 'unknown' },
    { name: "Music", img:  "./images/music.png", userId: 'unknown' },
    { name:  "Profession", img:  "./images/job.png", userId: 'unknown' },
    { name:  "Weather", img:  "./images/weather.png", userId: 'unknown' },
    { name: "Tales", img:  "./images/magic-book.png", userId: 'unknown' },
    { name:  "Beverages", img:   "./images/beverage.png", userId: 'unknown' },
    { name: "Nature", img:  "./images/nature.png", userId: 'unknown' },
    
  ],
  words: [
    { eng: "Cure", rus: "Лечить", img: "./images/cure.png", sound: "./sounds/cure.mp3", category: "Action A", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Wash", rus: "Мыть", img: "./images/wash.png", sound: "./sounds/wash.mp3", category: "Action A", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Dance", rus: "Танцевать", img: "./images/dance.png", sound: "./sounds/dance.mp3", category: "Action A", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Swim", rus: "Плавать", img: "./images/swim.png", sound: "./sounds/swim.mp3", category: "Action A", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Read", rus: "Читать", img:  "./images/read.png", sound: "./sounds/read.mp3", category: "Action A", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Draw", rus: "Рисовать", img: "./images/draw.png", sound:  "./sounds/draw.mp3", category: "Action A", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Cry", rus: "Плакать", img: "./images/cry.png", sound: "./sounds/cry.mp3", category: "Action A", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Write", rus: "Писать", img: "./images/write.png", sound: "./sounds/write.mp3", category: "Action A", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    
    { eng: "Wink", rus: "Подмигивать", img: "./images/wink.png", sound: "./sounds/wink.mp3", category: "Action B", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Eat", rus: "Есть", img:  "./images/eat.png", sound: "./sounds/eat.mp3", category: "Action B", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Kiss", rus: "Целовать", img: "./images/kiss.png", sound: "./sounds/kiss.mp3", category: "Action B", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Buy", rus: "Покупать", img: "./images/buy.png", sound: "./sounds/buy.mp3", category: "Action B", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Joy", rus: "Радоваться", img: "./images/joy.png", sound:  "./sounds/joy.mp3", category: "Action B", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Argue", rus: "Спорить", img: "./images/argue.png", sound: "./sounds/argue.mp3", category: "Action B", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Greet", rus: "Приветствовать", img:  "./images/greet.png", sound: "./sounds/greet.mp3", category: "Action B", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Think", rus: "Думать", img: "./images/think.png", sound: "./sounds/think.mp3", category: "Action B", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    
    { eng: "cupcake", rus: "кекс", img: "./images/cupcake.png", sound: "./sounds/cupcake.mp3", category: "Food", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "bread", rus: "хлеб", img: "./images/bread.png", sound: "./sounds/bread.mp3", category: "Food", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "blueberries", rus: "черника", img: "./images/blueberries.png", sound: "./sounds/blueberries.mp3", category: "Food", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "pizza", rus: "пицца", img: "./images/pizza.png", sound: "./sounds/pizza.mp3", category: "Food", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "noodles", rus: "лапша", img: "./images/noodles.png", sound: "./sounds/noodles.mp3", category: "Food", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "meat", rus: "мясо", img: "./images/meat.png", sound: "./sounds/meat.mp3", category: "Food", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "broccoli", rus: "броколи", img: "./images/broccoli.png", sound: "./sounds/broccoli.mp3", category: "Food", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "orange", rus: "апельсин", img: "./images/orange.png", sound: "./sounds/orange.mp3", category: "Food", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
   
    { eng: "Fork", rus: "Вилка", img: "./images/fork.png", sound: "./sounds/fork.mp3", category: "Dishes", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Spoon", rus: "Ложка", img: "./images/Spoon.png", sound: "./sounds/spoon.mp3", category: "Dishes", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Knife", rus: "Нож", img: "./images/knife.png", sound: "./sounds/knife.mp3", category: "Dishes", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Mug", rus: "Кружка", img: "./images/mug.png", sound: "./sounds/mug.mp3", category: "Dishes", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "plate", rus: "Тарелка", img: "./images/plate.png", sound: "./sounds/plate.mp3", category: "Dishes", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Pan", rus: "Сковорода", img: "./images/pan.png", sound: "./sounds/pan.mp3", category: "Dishes", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Teapot", rus: "Чайник", img: "./images/teapot.png", sound: "./sounds/teapot.mp3", category: "Dishes", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Glass", rus: "Стакан", img: "./images/glass.png", sound: "./sounds/glass.mp3", category: "Dishes", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    
    { eng: "Parrot", rus: "Попугай", img: "./images/parrot.png", sound: "./sounds/parrot.mp3", category: "Pets", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Turtle", rus: "Черепаха", img: "./images/turtle.png", sound: "./sounds/turtle.mp3", category: "Pets", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Cat", rus: "Кот", img: "./images/cat.png", sound: "./sounds/cat.mp3", category: "Pets", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Hamster", rus: "Хомяк", img: "./images/hamster.png", sound: "./sounds/hamster.mp3", category: "Pets", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Dog", rus: "Собака", img: "./images/dog.png", sound: "./sounds/dog.mp3", category: "Pets", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Rabbit", rus: "Кролик", img: "./images/rabbit.png", sound: "./sounds/rabbit.mp3", category: "Pets", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Fish", rus: "Рыба", img: "./images/fish.png", sound: "./sounds/fish.mp3", category: "Pets", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Frog", rus: "Лягушка", img: "./images/frog.png", sound: "./sounds/frog.mp3", category: "Pets", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    
    { eng: "Horse", rus: "Лошадь", img: "./images/horse.png", sound: "./sounds/horse.mp3", category: "Animals", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Chicken", rus: "Курица", img: "./images/chicken.png", sound: "./sounds/chicken.mp3", category: "Animals", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Giraffe", rus: "Жираф", img: "./images/giraffe.png", sound: "./sounds/giraffe.mp3", category: "Animals", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Cow", rus: "Корова", img: "./images/cow.png", sound: "./sounds/cow.mp3", category: "Animals", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Lion", rus: "Лев", img: "./images/lion.png", sound: "./sounds/lion.mp3", category: "Animals", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Pig", rus: "Свинья", img: "./images/pig.png", sound: "./sounds/pig.mp3", category: "Animals", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Sheep", rus: "Овечка", img: "./images/sheep.png", sound: "./sounds/sheep.mp3", category: "Animals", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Dolphin", rus: "Дельфин", img: "./images/dolphin.png", sound: "./sounds/dolphin.mp3", category: "Animals", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    
    { eng: "Shirt", rus: "Рубашка", img: "./images/shirt.png", sound: "./sounds/shirt.mp3", category: "Clothes", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Pants", rus: "Штаны", img: "./images/pants.png", sound: "./sounds/pants.mp3", category: "Clothes", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Skirt", rus: "Юбка", img: "./images/skirt.png", sound: "./sounds/skirt.mp3", category: "Clothes", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Coat", rus: "Пальто", img: "./images/coat.png", sound: "./sounds/coat.mp3", category: "Clothes", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Dress", rus: "Платье", img: "./images/dress.png", sound: "./sounds/dress.mp3", category: "Clothes", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Shoe", rus: "Туфли", img: "./images/shoe.png", sound: "./sounds/shoe.mp3", category: "Clothes", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Boot", rus: "Ботинок", img: "./images/boot.png", sound: "./sounds/boot.mp3", category: "Clothes", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Blouse", rus: "Блузка", img: "./images/blouse.png", sound: "./sounds/blouse.mp3", category: "Clothes", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },

    { eng: "Angry", rus: "Сердитый", img: "./images/angry.png", sound: "./sounds/angry.mp3", category: "Emotion", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Smile", rus: "Улыбающийся", img: "./images/smile.png", sound: "./sounds/smile.mp3", category: "Emotion", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Sad", rus: "Грустный", img: "./images/sad.png", sound: "./sounds/sad.mp3", category: "Emotion", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Scared", rus: "Испуганный", img: "./images/scared.png", sound: "./sounds/scared.mp3", category: "Emotion", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Laugh", rus: "Смеющийся", img: "./images/laugh.png", sound: "./sounds/laugh.mp3", category: "Emotion", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Tired", rus: "Уставший", img: "./images/tired.png", sound: "./sounds/tired.mp3", category: "Emotion", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Happy", rus: "Счастливый", img: "./images/happy.png", sound: "./sounds/happy.mp3", category: "Emotion", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Surprised", rus: "Удивленный", img: "./images/surprised.png", sound: "./sounds/surprised.mp3", category: "Emotion", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },

    
    { eng: "leg", rus: "Нога", img: "./images/leg.png", sound: "./sounds/leg.mp3", category: "Body", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "arm", rus: "Рука", img: "./images/arm.png", sound: "./sounds/arm.mp3", category: "Body", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "head", rus: "Голова", img: "./images/head.png", sound: "./sounds/head.mp3", category: "Body", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "hand", rus: "Ладонь", img: "./images/hand.png", sound: "./sounds/hand.mp3", category: "Body", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "mouth", rus: "Рот", img: "./images/mouth.png", sound: "./sounds/mouth.mp3", category: "Body", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "eye", rus: "Глаз", img: "./images/eye.png", sound: "./sounds/eye.mp3", category: "Body", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "foot", rus: "Стопа", img: "./images/foot.png", sound: "./sounds/foot.mp3", category: "Body", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "neck", rus: "Шея", img: "./images/neck.png", sound: "./sounds/neck.mp3", category: "Body", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },

    { eng: "sun", rus: "Солнце", img: "./images/sun.png", sound: "./sounds/sun.mp3", category: "Space", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "comet", rus: "Комета", img: "./images/comet.png", sound: "./sounds/comet.mp3", category: "Space", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "earth", rus: "Земля", img: "./images/earth.png", sound: "./sounds/earth.mp3", category: "Space", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "venus", rus: "Венера", img: "./images/venus.png", sound: "./sounds/venus.mp3", category: "Space", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "astronaut", rus: "Астронавт", img: "./images/astronaut.png", sound: "./sounds/astronaut.mp3", category: "Space", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "meteorite", rus: "Метеорит", img: "./images/meteorite.png", sound: "./sounds/meteorite.mp3", category: "Space", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Space ship", rus: "Космический корбаль", img: "./images/space-ship.png", sound: "./sounds/space-ship.mp3", category: "Space", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "Milky Way", rus: "Млечный путь", img: "./images/milky-way.png", sound: "./sounds/milky-way.mp3", category: "Space", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },

    { eng: "domra", rus: "Домра", img: "./images/domra.png", sound: "./sounds/domra.mp3", category: "Music", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "accordion", rus: "Аккордеон", img: "./images/accordion.png", sound: "./sounds/accordion.mp3", category: "Music", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "violin", rus: "Скрипка", img: "./images/violin.png", sound: "./sounds/violin.mp3", category: "Music", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "cornet", rus: "Корнет", img: "./images/cornet.png", sound: "./sounds/cornet.mp3", category: "Music", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "guitar", rus: "Гитара", img: "./images/guitar.png", sound: "./sounds/guitar.mp3", category: "Music", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "drums", rus: "Барабаны", img: "./images/drums.png", sound: "./sounds/drums.mp3", category: "Music", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "piano", rus: "Фортепиано", img: "./images/piano.png", sound: "./sounds/piano.mp3", category: "Music", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "xylophone", rus: "Ксилофон", img: "./images/xylophone.png", sound: "./sounds/xylophone.mp3", category: "Music", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    
    { eng: "doctor", rus: "Доктор", img: "./images/doctor.png", sound: "./sounds/doctor.mp3", category: "Profession", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "programmer", rus: "Программист", img: "./images/programmer.png", sound: "./sounds/programmer.mp3", category: "Profession", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "scientist", rus: "Ученый", img: "./images/scientist.png", sound: "./sounds/scientist.mp3", category: "Profession", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "teacher", rus: "Учитель", img: "./images/teacher.png", sound: "./sounds/teacher.mp3", category: "Profession", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "builder", rus: "Строитель", img: "./images/builder.png", sound: "./sounds/builder.mp3", category: "Profession", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "nurse", rus: "Медсестра", img: "./images/nurse.png", sound: "./sounds/nurse.mp3", category: "Profession", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "chef", rus: "Шеф-повар", img: "./images/chef.png", sound: "./sounds/chef.mp3", category: "Profession", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "sailor", rus: "Моряк", img: "./images/sailor.png", sound: "./sounds/sailor.mp3", category: "Profession", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    
    { eng: "wind", rus: "Ветер", img: "./images/wind.png", sound: "./sounds/wind.mp3", category: "Weather", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "rainbow", rus: "Радуга", img: "./images/rainbow.png", sound: "./sounds/rainbow.mp3", category: "Weather", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "rain", rus: "Дождь", img: "./images/rain.png", sound: "./sounds/rain.mp3", category: "Weather", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "sunny", rus: "Солнечно", img: "./images/sunny.png", sound: "./sounds/sunny.mp3", category: "Weather", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "snow", rus: "Снег", img: "./images/snow.png", sound: "./sounds/snow.mp3", category: "Weather", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "hot", rus: "Жара", img: "./images/hot.png", sound: "./sounds/hot.mp3", category: "Weather", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "thunder", rus: "Гром", img: "./images/thunder.png", sound: "./sounds/thunder.mp3", category: "Weather", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "cold", rus: "Холод", img: "./images/cold.png", sound: "./sounds/cold.mp3", category: "Weather", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },

    { eng: "witch", rus: "Ведьма", img: "./images/witch.png", sound: "./sounds/witch.mp3", category: "Tales", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "prince", rus: "Принц", img: "./images/prince.png", sound: "./sounds/prince.mp3", category: "Tales", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "fairy", rus: "Фея", img: "./images/fairy.png", sound: "./sounds/fairy.mp3", category: "Tales", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "elf", rus: "Эльф", img: "./images/elf.png", sound: "./sounds/elf.mp3", category: "Tales", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "knight", rus: "Рыцарь", img: "./images/knight.png", sound: "./sounds/knight.mp3", category: "Tales", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "king", rus: "Король", img: "./images/king.png", sound: "./sounds/king.mp3", category: "Tales", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "princess", rus: "Принцесса", img: "./images/princess.png", sound: "./sounds/princess.mp3", category: "Tales", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "goblin", rus: "Гоблин", img: "./images/goblin.png", sound: "./sounds/goblin.mp3", category: "Tales", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },

    
    { eng: "water", rus: "Вода", img: "./images/water.png", sound: "./sounds/water.mp3", category: "Beverages", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "juice", rus: "Сок", img: "./images/juice.png", sound: "./sounds/juice.mp3", category: "Beverages", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "milk", rus: "Молоко", img: "./images/milk.png", sound: "./sounds/milk.mp3", category: "Beverages", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "tea", rus: "Чай", img: "./images/tea.png", sound: "./sounds/tea.mp3", category: "Beverages", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "coffee", rus: "Кофе", img: "./images/coffee.png", sound: "./sounds/coffee.mp3", category: "Beverages", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "lemonade", rus: "Лимонад", img: "./images/lemonade.png", sound: "./sounds/lemonade.mp3", category: "Beverages", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "cacao", rus: "Какао", img: "./images/cacao.png", sound: "./sounds/cacao.mp3", category: "Beverages", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "milkshake", rus: "Молочный коктейль", img: "./images/milkshake.png", sound: "./sounds/milkshake.mp3", category: "Beverages", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },

    
    { eng: "tree", rus: "Дерево", img: "./images/tree.png", sound: "./sounds/tree.mp3", category: "Nature", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "grass", rus: "Трава", img: "./images/grass.png", sound: "./sounds/grass.mp3", category: "Nature", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "lake", rus: "Озеро", img: "./images/lake.png", sound: "./sounds/lake.mp3", category: "Nature", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "mountain", rus: "Гора", img: "./images/mountain.png", sound: "./sounds/mountain.mp3", category: "Nature", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "waterfall", rus: "Водопад", img: "./images/waterfall.png", sound: "./sounds/waterfall.mp3", category: "Nature", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "wave", rus: "Волна", img: "./images/wave.png", sound: "./sounds/wave.mp3", category: "Nature", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "stone", rus: "Камень", img: "./images/stone.png", sound: "./sounds/stone.mp3", category: "Nature", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
    { eng: "flower", rus: "Цветок", img: "./images/flower.png", sound: "./sounds/flower.mp3", category: "Nature", Statistics: { clicks: 0, wrong: 0, right: 0, percent: 0 }, userId: 'unknown' },
  ]
}

export default initState



